%SSO source code v2.0, Generated by Hisham A. Shehadeh, 2021. 

			      %-------------------------------------------%
                              %         Adopted from:                     %           
                              %-------------------------------------------%

%Shehadeh, H. A. (2021). A hybrid sperm swarm optimization and gravitational search algorithm (HSSOGSA) 
%for global optimization. Neural Computing and Applications, 1-14.

 			      %-------------------------------------------%
                              %         Adopted from:                     %           
                              %-------------------------------------------%
% Shehadeh, H. A., Ahmedy, I., & Idris, M. Y. I. (2018, September). 
%Empirical study of sperm swarm optimization algorithm. 
%In Proceedings of SAI Intelligent Systems Conference (pp. 1082-1104). Springer, Cham.

			      %-------------------------------------------%
                              %         Adopted from:                     %           
                              %-------------------------------------------%

%Shehadeh, H. A., Ahmedy, I., & Idris, M. Y. I. (2018, February). 
%Sperm swarm optimization algorithm for optimizing wireless sensor network challenges. 
%In Proceedings of the 6th International Conference on Communications and Broadband Networking (pp. 53-59).
clear all
clc

N = 30;                        % Size of the swarm " no of objects "
Max_Iteration  = 1000;              % Maximum number of "iterations"

Benchmark_Function_ID= 2 %Benchmark function ID

[sgBestScore,sgBest,GlobalBestCost]= SSO(Benchmark_Function_ID, N, Max_Iteration)

sgBest
sgBestScore
semilogy(GlobalBestCost,'-r');
title(['\fontsize{12}\bf Benchmark Function: F',num2str(Benchmark_Function_ID)]);
xlabel('\fontsize{12}\bf Iteration');ylabel('\fontsize{12}\bf Fitness(Best-so-far)');
legend('\fontsize{10}\bf SSO',1);